version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
      - '6380:6380'
  app:
    image: model
    env_file:
      - .env
    container_name: model
    ports:
      - 5002:8000
