version: '3.7'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: database
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - '5432:5432'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
      - '6380:6380'
  app:
    image: model
    container_name: model
    ports:
      - 8000:8000

volumes:
  dbdata:
    driver: local
