version: '3.8'
services:
  app:
    image: model_${ENV}
    container_name: model_${ENV}
    environment:
      - ENV=${ENV}
    env_file:
      - ${ENV_FILE}
    ports:
      - ${APP_PORT}:8000
    networks:
      - vove
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-1
        awslogs-group: vove-model-${ENV}
        tag: '{{ with split .ImageName ":" }}{{join . "_"}}{{end}}-{{.ID}}'

networks:
  vove:
    name: vove
    external: true