version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '${REDIS_PORT}:6379'
  app:
    image: model
    container_name: model
    ports:
      - ${DB_PORT}:8000
    networks:
      - vove
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-1
        awslogs-group: vove-model-${ENV}
        tag: '{{ with split .ImageName ":" }}{{join . "_"}}{{end}}-{{.ID}}'

networks:
  vove:
    name: vove
    external: true
