"""auto-generate migration

Revision ID: 81f11d991dc0
Revises: 
Create Date: 2023-05-01 10:03:28.872972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f11d991dc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_window',
    sa.Column('sliding_size', sa.Integer(), nullable=True),
    sa.Column('start_ts', sa.Integer(), nullable=True),
    sa.Column('end_ts', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_log',
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('time_window_id', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.Integer(), nullable=True),
    sa.Column('minimum_temperature', sa.Float(), nullable=True),
    sa.Column('maximum_temperature', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('relative_humidity', sa.Float(), nullable=True),
    sa.Column('heat_index', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('wind_chill', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('precipitation_cover', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('sea_level_pressure', sa.Float(), nullable=True),
    sa.Column('weather_type', sa.String(length=500), nullable=True),
    sa.Column('conditions', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['time_window_id'], ['time_window.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_log')
    op.drop_table('time_window')
    op.drop_table('location')
    # ### end Alembic commands ###
