"""drop predicted relationship

Revision ID: bfc05764ff21
Revises: d7f6b4fa4146
Create Date: 2023-05-13 22:20:24.703258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc05764ff21'
down_revision = 'd7f6b4fa4146'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('predicted_log_time_window_id_fkey', 'predicted_log', type_='foreignkey')
    op.drop_column('predicted_log', 'time_window_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_log', sa.Column('time_window_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('predicted_log_time_window_id_fkey', 'predicted_log', 'time_window', ['time_window_id'], ['id'])
    # ### end Alembic commands ###
