"""add index for foreign key column

Revision ID: 699a821c1535
Revises: 0814f4e17f09
Create Date: 2023-05-13 23:52:17.070911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699a821c1535'
down_revision = '0814f4e17f09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_predicted_log_location_id'), 'predicted_log', ['location_id'], unique=False)
    op.create_index(op.f('ix_weather_log_date_time'), 'weather_log', ['date_time'], unique=False)
    op.create_index(op.f('ix_weather_log_location_id'), 'weather_log', ['location_id'], unique=False)
    op.create_index(op.f('ix_weather_log_time_window_id'), 'weather_log', ['time_window_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_log_time_window_id'), table_name='weather_log')
    op.drop_index(op.f('ix_weather_log_location_id'), table_name='weather_log')
    op.drop_index(op.f('ix_weather_log_date_time'), table_name='weather_log')
    op.drop_index(op.f('ix_predicted_log_location_id'), table_name='predicted_log')
    # ### end Alembic commands ###
