"""update predicted log value to float

Revision ID: af1b953e1d97
Revises: 699a821c1535
Create Date: 2023-05-14 17:53:01.089684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1b953e1d97'
down_revision = '699a821c1535'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='predicted_log',
        column_name='value',
        type_=sa.Float
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='predicted_log',
        column_name='value',
        type_=sa.Float
    )
    # ### end Alembic commands ###
