"""add index for created at

Revision ID: 056c8bd1b0a8
Revises: bfc05764ff21
Create Date: 2023-05-13 22:56:32.500580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056c8bd1b0a8'
down_revision = 'bfc05764ff21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_location_created_at'), 'location', ['created_at'], unique=False)
    op.create_index(op.f('ix_predicted_log_created_at'), 'predicted_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_predicted_var_created_at'), 'predicted_var', ['created_at'], unique=False)
    op.create_index(op.f('ix_synced_file_created_at'), 'synced_file', ['created_at'], unique=False)
    op.create_index(op.f('ix_time_window_created_at'), 'time_window', ['created_at'], unique=False)
    op.create_index(op.f('ix_weather_log_created_at'), 'weather_log', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_log_created_at'), table_name='weather_log')
    op.drop_index(op.f('ix_time_window_created_at'), table_name='time_window')
    op.drop_index(op.f('ix_synced_file_created_at'), table_name='synced_file')
    op.drop_index(op.f('ix_predicted_var_created_at'), table_name='predicted_var')
    op.drop_index(op.f('ix_predicted_log_created_at'), table_name='predicted_log')
    op.drop_index(op.f('ix_location_created_at'), table_name='location')
    # ### end Alembic commands ###
