"""generate third party location to cache

Revision ID: 4a4967209671
Revises: af1b953e1d97
Create Date: 2023-05-20 16:46:46.717325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4967209671'
down_revision = 'af1b953e1d97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('third_party_location',
    sa.Column('location_code', sa.String(length=255), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_third_party_location_created_at'), 'third_party_location', ['created_at'], unique=False)
    op.create_index(op.f('ix_third_party_location_location_code'), 'third_party_location', ['location_code'], unique=True)
    op.create_index(op.f('ix_third_party_location_location_id'), 'third_party_location', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_third_party_location_location_id'), table_name='third_party_location')
    op.drop_index(op.f('ix_third_party_location_location_code'), table_name='third_party_location')
    op.drop_index(op.f('ix_third_party_location_created_at'), table_name='third_party_location')
    op.drop_table('third_party_location')
    # ### end Alembic commands ###
