"""add predict time in predicted log

Revision ID: b394abb39d65
Revises: 4a4967209671
Create Date: 2023-05-23 08:55:23.521774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b394abb39d65'
down_revision = '4a4967209671'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_log', sa.Column('predict_time', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_predicted_log_predict_time'), 'predicted_log', ['predict_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predicted_log_predict_time'), table_name='predicted_log')
    op.drop_column('predicted_log', 'predict_time')
    # ### end Alembic commands ###
