"""add district and ward

Revision ID: 5cfb2523afa8
Revises: 21564d47794b
Create Date: 2023-06-09 19:27:14.751891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfb2523afa8'
down_revision = '21564d47794b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district',
    sa.Column('location_code', sa.String(length=255), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_district_created_at'), 'district', ['created_at'], unique=False)
    op.create_index(op.f('ix_district_location_code'), 'district', ['location_code'], unique=True)
    op.create_index(op.f('ix_district_location_id'), 'district', ['location_id'], unique=False)
    op.create_table('ward',
    sa.Column('location_code', sa.String(length=255), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('district_code', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_code'], ['district.location_code'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_created_at'), 'ward', ['created_at'], unique=False)
    op.create_index(op.f('ix_ward_district_code'), 'ward', ['district_code'], unique=False)
    op.create_index(op.f('ix_ward_location_code'), 'ward', ['location_code'], unique=True)
    op.create_index(op.f('ix_ward_location_id'), 'ward', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ward_location_id'), table_name='ward')
    op.drop_index(op.f('ix_ward_location_code'), table_name='ward')
    op.drop_index(op.f('ix_ward_district_code'), table_name='ward')
    op.drop_index(op.f('ix_ward_created_at'), table_name='ward')
    op.drop_table('ward')
    op.drop_index(op.f('ix_district_location_id'), table_name='district')
    op.drop_index(op.f('ix_district_location_code'), table_name='district')
    op.drop_index(op.f('ix_district_created_at'), table_name='district')
    op.drop_table('district')
    # ### end Alembic commands ###
