"""auto-generate migration

Revision ID: ae850d583f36
Revises: 81f11d991dc0
Create Date: 2023-05-01 16:05:43.392206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae850d583f36'
down_revision = '81f11d991dc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predicted_log',
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('time_window_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('model_file_path', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['time_window_id'], ['time_window.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predicted_var',
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('time_window_id', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['time_window_id'], ['time_window.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predicted_var')
    op.drop_table('predicted_log')
    # ### end Alembic commands ###
